Proxy support added
teachbase/webinar_ru pull request #5
Opened 2022-12-08 10:41 UTC by fargelus

2022-12-08 10:58 UTC, AlexanderShvaykin requested changes

2022-12-08 10:58 UTC, AlexanderShvaykin commented on lib/webinar_ru/api/v3/client.rb
> +        path { proxy || "https://#{domain || DOMAIN}.#{host || HOST}/v#{VERSION}" }
И что получиться что запросы будут на прокси уходить?

2022-12-08 10:58 UTC, AlexanderShvaykin commented on lib/webinar_ru/api/v3/client.rb
> +        path { proxy || "https://#{domain || DOMAIN}.#{host || HOST}/v#{VERSION}" }
Имелось ввиду этот прокси
https://ruby-doc.org/stdlib-2.7.3/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new

2022-12-08 11:28 UTC, klondaiker commented on lib/webinar_ru/api/v3/client.rb
> +        path { proxy || "https://#{domain || DOMAIN}.#{host || HOST}/v#{VERSION}" }
Походу нельзя просто передать прокси , придется форкать или контрибютить

https://github.com/evilmartians/evil-client/blob/74619164257f237473eacedd4f8a756d4e8aca27/lib/evil/client/connection.rb#L29

https://ruby-doc.org/stdlib-2.7.3/libdoc/net/http/rdoc/Net/HTTP.html#method-c-start

2022-12-13 10:32 UTC, AlexanderShvaykin approved these changes

2022-12-14 09:35 UTC, merged